# Generated by Django 5.2.7 on 2025-11-14 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
