# Generated by Django 5.2.7 on 2025-11-14 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_reservation_location_alter_reservation_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="user",
            new_name="host",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="room",
            name="location",
        ),
        migrations.AddField(
            model_name="reservation",
            name="description",
            field=models.TextField(default="No description provided"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="name",
            field=models.CharField(default="Untitled Reservation", max_length=200),
        ),
        migrations.AddField(
            model_name="reservation",
            name="participants",
            field=models.ManyToManyField(
                blank=True, related_name="joined_meetups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_time",
            field=models.DateTimeField(default="2025-11-13 13:00"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time",
            field=models.DateTimeField(default="2025-11-13 12:00"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
